module.exports = {
  id: 4884199014561,
  admin_graphql_api_id: "gid://shopify/Order/4884199014561",
  app_id: 580111,
  browser_ip: "107.77.223.130",
  buyer_accepts_marketing: true,
  cancel_reason: null,
  cancelled_at: null,
  cart_token: "dfd4153f49214e2625561b11715d8270",
  checkout_id: 25960421327009,
  checkout_token: "c443b8928ff2c45a954ab5d2f080bbe2",
  client_details: {
    accept_language: "en-US,en;q=0.9,he-IL;q=0.8,he;q=0.7",
    browser_height: 730,
    browser_ip: "107.77.223.130",
    browser_width: 412,
    session_hash: null,
    user_agent:
      "Mozilla/5.0 (Linux; Android 11; SM-G973U Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.101 Mobile Safari/537.36 Instagram 224.2.0.20.116 Android (30/11; 420dpi; 1080x2042; samsung; SM-G973U; beyond1q; qcom; en_US; 354065949)",
  },
  closed_at: "2022-03-14T12:11:20-04:00",
  confirmed: true,
  contact_email: "eransco@gmail.com",
  created_at: "2022-03-11T13:10:08-05:00",
  currency: "USD",
  current_subtotal_price: "81.00",
  current_subtotal_price_set: {
    shop_money: {
      amount: "81.00",
      currency_code: "USD",
    },
    presentment_money: {
      amount: "81.00",
      currency_code: "USD",
    },
  },
  current_total_discounts: "0.00",
  current_total_discounts_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "USD",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "USD",
    },
  },
  current_total_duties_set: null,
  current_total_price: "81.00",
  current_total_price_set: {
    shop_money: {
      amount: "81.00",
      currency_code: "USD",
    },
    presentment_money: {
      amount: "81.00",
      currency_code: "USD",
    },
  },
  current_total_tax: "0.00",
  current_total_tax_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "USD",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "USD",
    },
  },
  customer_locale: "en-US",
  device_id: null,
  discount_codes: [],
  email: "eransco@gmail.com",
  estimated_taxes: false,
  financial_status: "paid",
  fulfillment_status: "fulfilled",
  gateway: "shopify_payments",
  landing_site: "/",
  landing_site_ref: null,
  location_id: null,
  name: "#1039",
  note: "",
  note_attributes: [
    {
      name: "answers",
      value:
        '[{"question":{"id":1},"answer":"Eran"},{"question":{"id":2},"weights":{"Bio Age":{"value":4500,"base":100},"Age":{"value":2250,"base":"50"}},"answer":"1977"},{"question":{"id":3},"answer":"Male","black_list_actives":null},{"question":{"id":21},"weights":{"Pollution":{"value":3300,"base":33},"Sun":{"value":333.34000000000003,"base":10},"Temperature":{"value":0,"base":0},"Hydration":{"value":1000.005,"base":15}},"answer":"New York","city_id":"ChIJOwg_06VPwokRYv534QaPC8g"},{"question":{"id":6},"answer":"Moderately","slider_value":48.8236376101533,"weights":{"Sensitivity":{"value":4882.36376101533,"base":100}},"black_list_actives":[]},{"question":{"id":7},"answer":"Normal / Combination","slider_value":49.3035466448172,"weights":{"Hydration":{"value":3451.2482651372043,"base":70}},"black_list_actives":[]},{"question":{"id":9},"weights":{"Color":{"value":2666.67,"base":100},"Sun":{"value":266.667,"base":10},"Hyperpigmentation":{"value":266.667,"base":10}},"answer":"4","black_list_actives":null},{"question":{"id":10},"answer":"Always","slider_value":89.6827918331856,"weights":{"Sun":{"value":1793.655836663712,"base":20}},"black_list_actives":[]},{"question":{"id":11},"answer":"No","slider_value":33.7825861578851,"weights":{"Hyperpigmentation":{"value":3040.432754209659,"base":90},"Sun":{"value":337.825861578851,"base":10}},"black_list_actives":[]},{"question":{"id":12},"answer":"Instant Burn","slider_value":68.8008962761066,"weights":{"Sun":{"value":4128.053776566396,"base":60}},"black_list_actives":[]},{"question":{"id":14},"answer":"eransco@gmail.com"},{"question":{"id":17},"answer":"Some","slider_value":36.7172215440697,"weights":{"Pores":{"value":3671.7221544069703,"base":100}},"black_list_actives":[]},{"question":{"id":15},"answer":"A Few Lines","slider_value":21.4805277327224,"weights":{"Lines":{"value":2148.05277327224,"base":100},"Age":{"value":644.415831981672,"base":30}},"black_list_actives":[]},{"question":{"id":18},"answer":"Some","slider_value":34.1220340116717,"weights":{"Blackheads":{"value":3412.2034011671703,"base":100}},"black_list_actives":[]},{"question":{"id":19},"weights":{"Allergies":{"value":0,"base":100}},"answer":"No","black_list_actives":null},{"question":{"id":25},"answer":"<4","slider_value":5.99923080781901,"weights":{"Sleep":{"value":4998.077019547524,"base":100}},"black_list_actives":[]},{"question":{"id":27},"answer":"6","slider_value":32.0335100245807,"weights":{"Hydration":{"value":480.5026503687105,"base":15}},"black_list_actives":[]},{"question":{"id":29},"answer":"Low","slider_value":55.6242997842918,"weights":{"Oxygenation":{"value":5562.42997842918,"base":100}},"black_list_actives":[]}]',
    },
    {
      name: "profile",
      value:
        '{"Skin Sensitivity":[{"name":"Sensitivity","percentage":48.8236376101533},{"name":"Hydration","percentage":49.31755915505914},{"name":"Sun","percentage":62.35947704371781},{"name":"Hyperpigmentation","percentage":33.07099754209659},{"name":"Redness","percentage":0}],"Skin Characteristics":[{"name":"Breakouts","percentage":0},{"name":"Lines","percentage":21.480527732722397},{"name":"Pores","percentage":36.7172215440697},{"name":"Blackheads","percentage":34.1220340116717}],"Environmental Factors":[{"name":"Pollution","percentage":100},{"name":"Stress","percentage":0},{"name":"Oxygenation","percentage":55.6242997842918}]}',
    },
    {
      name: "actives",
      value: '["Base","Moringa","Chia","Gotu Kola","Dragon\'s Blood","Oatmeal","Coconut","Chamomile"]',
    },
  ],
  number: 39,
  order_number: 1039,
  order_status_url: "https://localhost:3001/48557752481/orders/494d781f1edc1b0101e520b16f132c65/authenticate?key=8c15f18557e37ab98b7b37b1104a4734",
  original_total_duties_set: null,
  payment_gateway_names: ["shopify_payments"],
  phone: null,
  presentment_currency: "USD",
  processed_at: "2022-03-11T13:10:03-05:00",
  processing_method: "direct",
  reference: null,
  referring_site: "https://l.instagram.com/",
  source_identifier: null,
  source_name: "web",
  source_url: null,
  subtotal_price: "81.00",
  subtotal_price_set: {
    shop_money: {
      amount: "81.00",
      currency_code: "USD",
    },
    presentment_money: {
      amount: "81.00",
      currency_code: "USD",
    },
  },
  tags: "",
  tax_lines: [],
  taxes_included: false,
  test: false,
  token: "494d781f1edc1b0101e520b16f132c65",
  total_discounts: "0.00",
  total_discounts_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "USD",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "USD",
    },
  },
  total_line_items_price: "81.00",
  total_line_items_price_set: {
    shop_money: {
      amount: "81.00",
      currency_code: "USD",
    },
    presentment_money: {
      amount: "81.00",
      currency_code: "USD",
    },
  },
  total_outstanding: "0.00",
  total_price: "81.00",
  total_price_set: {
    shop_money: {
      amount: "81.00",
      currency_code: "USD",
    },
    presentment_money: {
      amount: "81.00",
      currency_code: "USD",
    },
  },
  total_price_usd: "81.00",
  total_shipping_price_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "USD",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "USD",
    },
  },
  total_tax: "0.00",
  total_tax_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "USD",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "USD",
    },
  },
  total_tip_received: "0.00",
  total_weight: 255,
  updated_at: "2022-03-15T20:07:23-04:00",
  user_id: null,
  billing_address: {
    first_name: "Eran",
    address1: "241 Eldridge Street",
    phone: "(917) 283-1769",
    city: "New York",
    zip: "10002",
    province: "New York",
    country: "United States",
    last_name: "Socher",
    address2: "3F",
    company: "",
    latitude: 40.7226658,
    longitude: -73.98991269999999,
    name: "Eran Socher",
    country_code: "US",
    province_code: "NY",
  },
  customer: {
    id: 6018740715681,
    email: "eransco@gmail.com",
    accepts_marketing: true,
    created_at: "2022-03-11T13:09:14-05:00",
    updated_at: "2022-03-12T21:06:36-05:00",
    first_name: "Eran",
    last_name: "Socher",
    orders_count: 1,
    state: "disabled",
    total_spent: "81.00",
    last_order_id: 4884199014561,
    note: null,
    verified_email: true,
    multipass_identifier: null,
    tax_exempt: false,
    phone: null,
    tags: "",
    last_order_name: "#1039",
    currency: "USD",
    accepts_marketing_updated_at: "2022-03-11T13:09:14-05:00",
    marketing_opt_in_level: "single_opt_in",
    tax_exemptions: [],
    email_marketing_consent: {
      state: "subscribed",
      opt_in_level: "single_opt_in",
      consent_updated_at: null,
    },
    sms_marketing_consent: null,
    admin_graphql_api_id: "gid://shopify/Customer/6018740715681",
    default_address: {
      id: 7239153418401,
      customer_id: 6018740715681,
      first_name: "Eran",
      last_name: "Socher",
      company: "",
      address1: "241 Eldridge Street",
      address2: "3F",
      city: "New York",
      province: "New York",
      country: "United States",
      zip: "10002",
      phone: "(917) 283-1769",
      name: "Eran Socher",
      province_code: "NY",
      country_code: "US",
      country_name: "United States",
      default: true,
    },
  },
  discount_applications: [],
  fulfillments: [
    {
      id: 4383119540385,
      admin_graphql_api_id: "gid://shopify/Fulfillment/4383119540385",
      created_at: "2022-03-14T12:11:18-04:00",
      location_id: 55199531169,
      name: "#1039.1",
      order_id: 4884199014561,
      origin_address: {},
      receipt: {},
      service: "manual",
      shipment_status: "delivered",
      status: "success",
      tracking_company: "UPS®",
      tracking_number: "1ZY348370390287118",
      tracking_numbers: ["1ZY348370390287118"],
      tracking_url: "https://www.ups.com/WebTracking?loc=en_US&requester=ST&trackNums=1ZY348370390287118",
      tracking_urls: ["https://www.ups.com/WebTracking?loc=en_US&requester=ST&trackNums=1ZY348370390287118"],
      updated_at: "2022-03-15T20:07:23-04:00",
      line_items: [
        {
          id: 12304305422497,
          admin_graphql_api_id: "gid://shopify/LineItem/12304305422497",
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 1,
          name: "Oatmeal",
          origin_location: {
            id: 3271783514273,
            country_code: "US",
            province_code: "NY",
            name: "Created By",
            address1: "4702 2nd Avenue",
            address2: "",
            city: "Brooklyn",
            zip: "11232",
          },
          price: "4.50",
          price_set: {
            shop_money: {
              amount: "4.50",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "4.50",
              currency_code: "USD",
            },
          },
          product_exists: true,
          product_id: 7117745127585,
          properties: [
            {
              name: "score",
              value: "23.35",
            },
          ],
          quantity: 1,
          requires_shipping: true,
          sku: "2014",
          taxable: true,
          title: "Oatmeal",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "USD",
            },
          },
          variant_id: 41205127577761,
          variant_inventory_management: "shopify",
          variant_title: "",
          vendor: "Created By",
          tax_lines: [],
          duties: [],
          discount_allocations: [],
        },
        {
          id: 12304305455265,
          admin_graphql_api_id: "gid://shopify/LineItem/12304305455265",
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 1,
          name: "Moringa",
          origin_location: {
            id: 3271783514273,
            country_code: "US",
            province_code: "NY",
            name: "Created By",
            address1: "4702 2nd Avenue",
            address2: "",
            city: "Brooklyn",
            zip: "11232",
          },
          price: "5.50",
          price_set: {
            shop_money: {
              amount: "5.50",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "5.50",
              currency_code: "USD",
            },
          },
          product_exists: true,
          product_id: 7117738180769,
          properties: [
            {
              name: "score",
              value: "26.44",
            },
          ],
          quantity: 1,
          requires_shipping: true,
          sku: "2012",
          taxable: true,
          title: "Moringa",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "USD",
            },
          },
          variant_id: 41205119090849,
          variant_inventory_management: "shopify",
          variant_title: "",
          vendor: "Created By",
          tax_lines: [],
          duties: [],
          discount_allocations: [],
        },
        {
          id: 12304305488033,
          admin_graphql_api_id: "gid://shopify/LineItem/12304305488033",
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 1,
          name: "Gotu Kola",
          origin_location: {
            id: 3271783514273,
            country_code: "US",
            province_code: "NY",
            name: "Created By",
            address1: "4702 2nd Avenue",
            address2: "",
            city: "Brooklyn",
            zip: "11232",
          },
          price: "6.00",
          price_set: {
            shop_money: {
              amount: "6.00",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "6.00",
              currency_code: "USD",
            },
          },
          product_exists: true,
          product_id: 7117734838433,
          properties: [
            {
              name: "score",
              value: "24.39",
            },
          ],
          quantity: 1,
          requires_shipping: true,
          sku: "2010",
          taxable: true,
          title: "Gotu Kola",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "USD",
            },
          },
          variant_id: 41205114437793,
          variant_inventory_management: "shopify",
          variant_title: "",
          vendor: "Created By",
          tax_lines: [],
          duties: [],
          discount_allocations: [],
        },
        {
          id: 12304305520801,
          admin_graphql_api_id: "gid://shopify/LineItem/12304305520801",
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 1,
          name: "Dragon's Blood",
          origin_location: {
            id: 3271783514273,
            country_code: "US",
            province_code: "NY",
            name: "Created By",
            address1: "4702 2nd Avenue",
            address2: "",
            city: "Brooklyn",
            zip: "11232",
          },
          price: "6.00",
          price_set: {
            shop_money: {
              amount: "6.00",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "6.00",
              currency_code: "USD",
            },
          },
          product_exists: true,
          product_id: 7117731987617,
          properties: [
            {
              name: "score",
              value: "24.07",
            },
          ],
          quantity: 1,
          requires_shipping: true,
          sku: "2008",
          taxable: true,
          title: "Dragon's Blood",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "USD",
            },
          },
          variant_id: 41205111095457,
          variant_inventory_management: "shopify",
          variant_title: "",
          vendor: "Created By",
          tax_lines: [],
          duties: [],
          discount_allocations: [],
        },
        {
          id: 12304305553569,
          admin_graphql_api_id: "gid://shopify/LineItem/12304305553569",
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 1,
          name: "Coconut",
          origin_location: {
            id: 3271783514273,
            country_code: "US",
            province_code: "NY",
            name: "Created By",
            address1: "4702 2nd Avenue",
            address2: "",
            city: "Brooklyn",
            zip: "11232",
          },
          price: "5.00",
          price_set: {
            shop_money: {
              amount: "5.00",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "5.00",
              currency_code: "USD",
            },
          },
          product_exists: true,
          product_id: 7117723402401,
          properties: [
            {
              name: "score",
              value: "22.43",
            },
          ],
          quantity: 1,
          requires_shipping: true,
          sku: "2005",
          taxable: false,
          title: "Coconut",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "USD",
            },
          },
          variant_id: 41205095727265,
          variant_inventory_management: "shopify",
          variant_title: "",
          vendor: "Created By",
          tax_lines: [],
          duties: [],
          discount_allocations: [],
        },
        {
          id: 12304305586337,
          admin_graphql_api_id: "gid://shopify/LineItem/12304305586337",
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 1,
          name: "Chia",
          origin_location: {
            id: 3271783514273,
            country_code: "US",
            province_code: "NY",
            name: "Created By",
            address1: "4702 2nd Avenue",
            address2: "",
            city: "Brooklyn",
            zip: "11232",
          },
          price: "5.50",
          price_set: {
            shop_money: {
              amount: "5.50",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "5.50",
              currency_code: "USD",
            },
          },
          product_exists: true,
          product_id: 7117721665697,
          properties: [
            {
              name: "score",
              value: "24.67",
            },
          ],
          quantity: 1,
          requires_shipping: true,
          sku: "2004",
          taxable: false,
          title: "Chia",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "USD",
            },
          },
          variant_id: 41205091795105,
          variant_inventory_management: "shopify",
          variant_title: "",
          vendor: "Created By",
          tax_lines: [],
          duties: [],
          discount_allocations: [],
        },
        {
          id: 12304305619105,
          admin_graphql_api_id: "gid://shopify/LineItem/12304305619105",
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 1,
          name: "Chamomile",
          origin_location: {
            id: 3271783514273,
            country_code: "US",
            province_code: "NY",
            name: "Created By",
            address1: "4702 2nd Avenue",
            address2: "",
            city: "Brooklyn",
            zip: "11232",
          },
          price: "5.50",
          price_set: {
            shop_money: {
              amount: "5.50",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "5.50",
              currency_code: "USD",
            },
          },
          product_exists: true,
          product_id: 7117719109793,
          properties: [
            {
              name: "score",
              value: "22.18",
            },
          ],
          quantity: 1,
          requires_shipping: true,
          sku: "2003",
          taxable: false,
          title: "Chamomile",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "USD",
            },
          },
          variant_id: 41205087502497,
          variant_inventory_management: "shopify",
          variant_title: "",
          vendor: "Created By",
          tax_lines: [],
          duties: [],
          discount_allocations: [],
        },
        {
          id: 12304305651873,
          admin_graphql_api_id: "gid://shopify/LineItem/12304305651873",
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 240,
          name: "Base",
          origin_location: {
            id: 3271783514273,
            country_code: "US",
            province_code: "NY",
            name: "Created By",
            address1: "4702 2nd Avenue",
            address2: "",
            city: "Brooklyn",
            zip: "11232",
          },
          price: "43.00",
          price_set: {
            shop_money: {
              amount: "43.00",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "43.00",
              currency_code: "USD",
            },
          },
          product_exists: true,
          product_id: 5705461924001,
          properties: [
            {
              name: "score",
              value: "100.00",
            },
          ],
          quantity: 1,
          requires_shipping: true,
          sku: "1001",
          taxable: true,
          title: "Base",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "USD",
            },
          },
          variant_id: 36332638240929,
          variant_inventory_management: "shopify",
          variant_title: "",
          vendor: "Created By",
          tax_lines: [],
          duties: [],
          discount_allocations: [],
        },
        {
          id: 12311078731937,
          admin_graphql_api_id: "gid://shopify/LineItem/12311078731937",
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 1,
          name: "Blank",
          price: "0.00",
          price_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "USD",
            },
          },
          product_exists: true,
          product_id: 5873158619297,
          properties: [],
          quantity: 4,
          requires_shipping: true,
          sku: "2000",
          taxable: false,
          title: "Blank",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "USD",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "USD",
            },
          },
          variant_id: 36987054850209,
          variant_inventory_management: "shopify",
          variant_title: null,
          vendor: "Created By",
          tax_lines: [],
          duties: [],
          discount_allocations: [],
        },
      ],
    },
  ],
  line_items: [
    {
      id: 12304305422497,
      admin_graphql_api_id: "gid://shopify/LineItem/12304305422497",
      fulfillable_quantity: 0,
      fulfillment_service: "manual",
      fulfillment_status: "fulfilled",
      gift_card: false,
      grams: 1,
      name: "Oatmeal",
      origin_location: {
        id: 3271783514273,
        country_code: "US",
        province_code: "NY",
        name: "Created By",
        address1: "4702 2nd Avenue",
        address2: "",
        city: "Brooklyn",
        zip: "11232",
      },
      price: "4.50",
      price_set: {
        shop_money: {
          amount: "4.50",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "4.50",
          currency_code: "USD",
        },
      },
      product_exists: true,
      product_id: 7117745127585,
      properties: [
        {
          name: "score",
          value: "23.35",
        },
      ],
      quantity: 1,
      requires_shipping: true,
      sku: "2014",
      taxable: true,
      title: "Oatmeal",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "USD",
        },
      },
      variant_id: 41205127577761,
      variant_inventory_management: "shopify",
      variant_title: "",
      vendor: "Created By",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
    {
      id: 12304305455265,
      admin_graphql_api_id: "gid://shopify/LineItem/12304305455265",
      fulfillable_quantity: 0,
      fulfillment_service: "manual",
      fulfillment_status: "fulfilled",
      gift_card: false,
      grams: 1,
      name: "Moringa",
      origin_location: {
        id: 3271783514273,
        country_code: "US",
        province_code: "NY",
        name: "Created By",
        address1: "4702 2nd Avenue",
        address2: "",
        city: "Brooklyn",
        zip: "11232",
      },
      price: "5.50",
      price_set: {
        shop_money: {
          amount: "5.50",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "5.50",
          currency_code: "USD",
        },
      },
      product_exists: true,
      product_id: 7117738180769,
      properties: [
        {
          name: "score",
          value: "26.44",
        },
      ],
      quantity: 1,
      requires_shipping: true,
      sku: "2012",
      taxable: true,
      title: "Moringa",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "USD",
        },
      },
      variant_id: 41205119090849,
      variant_inventory_management: "shopify",
      variant_title: "",
      vendor: "Created By",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
    {
      id: 12304305488033,
      admin_graphql_api_id: "gid://shopify/LineItem/12304305488033",
      fulfillable_quantity: 0,
      fulfillment_service: "manual",
      fulfillment_status: "fulfilled",
      gift_card: false,
      grams: 1,
      name: "Gotu Kola",
      origin_location: {
        id: 3271783514273,
        country_code: "US",
        province_code: "NY",
        name: "Created By",
        address1: "4702 2nd Avenue",
        address2: "",
        city: "Brooklyn",
        zip: "11232",
      },
      price: "6.00",
      price_set: {
        shop_money: {
          amount: "6.00",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "6.00",
          currency_code: "USD",
        },
      },
      product_exists: true,
      product_id: 7117734838433,
      properties: [
        {
          name: "score",
          value: "24.39",
        },
      ],
      quantity: 1,
      requires_shipping: true,
      sku: "2010",
      taxable: true,
      title: "Gotu Kola",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "USD",
        },
      },
      variant_id: 41205114437793,
      variant_inventory_management: "shopify",
      variant_title: "",
      vendor: "Created By",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
    {
      id: 12304305520801,
      admin_graphql_api_id: "gid://shopify/LineItem/12304305520801",
      fulfillable_quantity: 0,
      fulfillment_service: "manual",
      fulfillment_status: "fulfilled",
      gift_card: false,
      grams: 1,
      name: "Dragon's Blood",
      origin_location: {
        id: 3271783514273,
        country_code: "US",
        province_code: "NY",
        name: "Created By",
        address1: "4702 2nd Avenue",
        address2: "",
        city: "Brooklyn",
        zip: "11232",
      },
      price: "6.00",
      price_set: {
        shop_money: {
          amount: "6.00",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "6.00",
          currency_code: "USD",
        },
      },
      product_exists: true,
      product_id: 7117731987617,
      properties: [
        {
          name: "score",
          value: "24.07",
        },
      ],
      quantity: 1,
      requires_shipping: true,
      sku: "2008",
      taxable: true,
      title: "Dragon's Blood",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "USD",
        },
      },
      variant_id: 41205111095457,
      variant_inventory_management: "shopify",
      variant_title: "",
      vendor: "Created By",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
    {
      id: 12304305553569,
      admin_graphql_api_id: "gid://shopify/LineItem/12304305553569",
      fulfillable_quantity: 0,
      fulfillment_service: "manual",
      fulfillment_status: "fulfilled",
      gift_card: false,
      grams: 1,
      name: "Coconut",
      origin_location: {
        id: 3271783514273,
        country_code: "US",
        province_code: "NY",
        name: "Created By",
        address1: "4702 2nd Avenue",
        address2: "",
        city: "Brooklyn",
        zip: "11232",
      },
      price: "5.00",
      price_set: {
        shop_money: {
          amount: "5.00",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "5.00",
          currency_code: "USD",
        },
      },
      product_exists: true,
      product_id: 7117723402401,
      properties: [
        {
          name: "score",
          value: "22.43",
        },
      ],
      quantity: 1,
      requires_shipping: true,
      sku: "2005",
      taxable: false,
      title: "Coconut",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "USD",
        },
      },
      variant_id: 41205095727265,
      variant_inventory_management: "shopify",
      variant_title: "",
      vendor: "Created By",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
    {
      id: 12304305586337,
      admin_graphql_api_id: "gid://shopify/LineItem/12304305586337",
      fulfillable_quantity: 0,
      fulfillment_service: "manual",
      fulfillment_status: "fulfilled",
      gift_card: false,
      grams: 1,
      name: "Chia",
      origin_location: {
        id: 3271783514273,
        country_code: "US",
        province_code: "NY",
        name: "Created By",
        address1: "4702 2nd Avenue",
        address2: "",
        city: "Brooklyn",
        zip: "11232",
      },
      price: "5.50",
      price_set: {
        shop_money: {
          amount: "5.50",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "5.50",
          currency_code: "USD",
        },
      },
      product_exists: true,
      product_id: 7117721665697,
      properties: [
        {
          name: "score",
          value: "24.67",
        },
      ],
      quantity: 1,
      requires_shipping: true,
      sku: "2004",
      taxable: false,
      title: "Chia",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "USD",
        },
      },
      variant_id: 41205091795105,
      variant_inventory_management: "shopify",
      variant_title: "",
      vendor: "Created By",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
    {
      id: 12304305619105,
      admin_graphql_api_id: "gid://shopify/LineItem/12304305619105",
      fulfillable_quantity: 0,
      fulfillment_service: "manual",
      fulfillment_status: "fulfilled",
      gift_card: false,
      grams: 1,
      name: "Chamomile",
      origin_location: {
        id: 3271783514273,
        country_code: "US",
        province_code: "NY",
        name: "Created By",
        address1: "4702 2nd Avenue",
        address2: "",
        city: "Brooklyn",
        zip: "11232",
      },
      price: "5.50",
      price_set: {
        shop_money: {
          amount: "5.50",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "5.50",
          currency_code: "USD",
        },
      },
      product_exists: true,
      product_id: 7117719109793,
      properties: [
        {
          name: "score",
          value: "22.18",
        },
      ],
      quantity: 1,
      requires_shipping: true,
      sku: "2003",
      taxable: false,
      title: "Chamomile",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "USD",
        },
      },
      variant_id: 41205087502497,
      variant_inventory_management: "shopify",
      variant_title: "",
      vendor: "Created By",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
    {
      id: 12304305651873,
      admin_graphql_api_id: "gid://shopify/LineItem/12304305651873",
      fulfillable_quantity: 0,
      fulfillment_service: "manual",
      fulfillment_status: "fulfilled",
      gift_card: false,
      grams: 240,
      name: "Base",
      origin_location: {
        id: 3271783514273,
        country_code: "US",
        province_code: "NY",
        name: "Created By",
        address1: "4702 2nd Avenue",
        address2: "",
        city: "Brooklyn",
        zip: "11232",
      },
      price: "43.00",
      price_set: {
        shop_money: {
          amount: "43.00",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "43.00",
          currency_code: "USD",
        },
      },
      product_exists: true,
      product_id: 5705461924001,
      properties: [
        {
          name: "score",
          value: "100.00",
        },
      ],
      quantity: 1,
      requires_shipping: true,
      sku: "1001",
      taxable: true,
      title: "Base",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "USD",
        },
      },
      variant_id: 36332638240929,
      variant_inventory_management: "shopify",
      variant_title: "",
      vendor: "Created By",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
    {
      id: 12311078731937,
      admin_graphql_api_id: "gid://shopify/LineItem/12311078731937",
      fulfillable_quantity: 0,
      fulfillment_service: "manual",
      fulfillment_status: "fulfilled",
      gift_card: false,
      grams: 1,
      name: "Blank",
      price: "0.00",
      price_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "USD",
        },
      },
      product_exists: true,
      product_id: 5873158619297,
      properties: [],
      quantity: 4,
      requires_shipping: true,
      sku: "2000",
      taxable: false,
      title: "Blank",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "USD",
        },
      },
      variant_id: 36987054850209,
      variant_inventory_management: "shopify",
      variant_title: null,
      vendor: "Created By",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
  ],
  payment_details: {
    credit_card_bin: "371300",
    avs_result_code: "Y",
    cvv_result_code: "M",
    credit_card_number: "•••• •••• •••• 1004",
    credit_card_company: "American Express",
  },
  payment_terms: null,
  refunds: [],
  shipping_address: {
    first_name: "Eran",
    address1: "241 Eldridge Street",
    phone: "(917) 283-1769",
    city: "New York",
    zip: "10002",
    province: "New York",
    country: "United States",
    last_name: "Socher",
    address2: "3F",
    company: "",
    latitude: 40.7226658,
    longitude: -73.98991269999999,
    name: "Eran Socher",
    country_code: "US",
    province_code: "NY",
  },
  shipping_lines: [
    {
      id: 3997918429345,
      carrier_identifier: null,
      code: "Standard",
      delivery_category: null,
      discounted_price: "0.00",
      discounted_price_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "USD",
        },
      },
      phone: null,
      price: "0.00",
      price_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "USD",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "USD",
        },
      },
      requested_fulfillment_service_id: null,
      source: "shopify",
      title: "Standard",
      tax_lines: [],
      discount_allocations: [],
    },
  ],
};
